# Pytorch Tutorial

Tensors Basics
 -> generalization of vectors and matrices.
 -> understood as multidimentional array.
 -> set of techniques known in ml in the training.
 -> operation of deep learning models can be described as tensors.
 -> replacement of Numpy to use the power of GPUs.

A PyTorch Tensor is basically the same as a numpy array: 
- it does not know anything about deep learning or computational graphs or gradients
- and is just a generic n-dimensional array to be used for arbitrary numeric computation.

Link to the documentation of pytorch tensor

In [ ]:
https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_tensor.html#:~:text=PyTorch%3A%20Tensors,-A%20third%20order&text=A%20PyTorch%20Tensor%20is%20basically,used%20for%20arbitrary%20numeric%20computation.

In [2]:
import torch

In [3]:
torch.__version__

'2.0.1'

In [4]:
import numpy as np

In [5]:
lst=[10,20,30]
arr=np.array(lst)

In [6]:
arr.dtype

dtype('int32')

# Converting Numpy array ----->  Pytorch Tensors

In [7]:
tensors=torch.from_numpy(arr)

The modified tensor and the numpy array share the same memory

In [8]:
tensors

tensor([10, 20, 30], dtype=torch.int32)

Similar to numpy we can use indexing to get the element

In [9]:
tensors[:2]

tensor([10, 20], dtype=torch.int32)

In [10]:
import math

In [11]:
dtype = torch.float #dtype mai sabhi values float honge
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

The device is explicitly set to "cpu," which means that all tensor operations will be executed on the CPU. This is the default device if you don't specify a different device, and it's commonly used when you either don't have a compatible GPU or you want to run computations on the CPU for various reasons, such as debugging or working with smaller datasets where GPU acceleration may not provide significant benefits.

linspace: It's a PyTorch function that generates evenly spaced values over a specified range.

In [12]:
number=np.array(x)
len(number)

2000

In [13]:
print("\ninput is ",x)
print("\noutput after applying sine operation is ",y)


input is  tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])

output after applying sine operation is  tensor([ 8.7423e-08, -3.1430e-03, -6.2863e-03,  ...,  6.2863e-03,
         3.1430e-03, -8.7423e-08])


To prevent from shared memory make one more copy

In [14]:
tensor_arr=torch.tensor(arr)
tensor_arr

tensor_arr[1]=200

In [15]:
print(tensor_arr)
arr

tensor([ 10, 200,  30], dtype=torch.int32)


array([10, 20, 30])

Some in-built features of pytorch

In [16]:
torch.zeros(2,3,dtype=torch.float)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.ones(2,3,dtype=torch.float)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Arithmetic Operations

In [18]:
a=torch.tensor([10,20,30],dtype=torch.float)
b=torch.tensor([10,10,10],dtype=torch.float)
print(a+ b)

tensor([20., 30., 40.])


In [19]:
c=torch.add(a,b)
c.shape

torch.Size([3])

In [20]:
c.sum()

tensor(90.)

# Dot product and multiply opeartion

dot product is when u wanna multiply 2 matrix and multiply is normal multiplication

In [21]:
p=torch.tensor([1,2,3],dtype=torch.float)
q=torch.tensor([2,2,2],dtype=torch.float)
print(torch.mul(p,q))
print(torch.dot(p,q))

tensor([2., 4., 6.])
tensor(12.)


In [22]:
print(p.mul(q))
p.dot(q)

tensor([2., 4., 6.])


tensor(12.)

In [23]:
matrix1=torch.tensor(([1,2,3],[4,5,6]))
matrix2=torch.tensor(([2,2,2],[2,2,2],[2,2,2]))
matrix1.matmul(matrix2)

tensor([[12, 12, 12],
        [30, 30, 30]])

4 types in which u can do matrix multiplication

In [24]:
matrix1.matmul(matrix2)

tensor([[12, 12, 12],
        [30, 30, 30]])

In [25]:
torch.matmul(matrix1,matrix2)

tensor([[12, 12, 12],
        [30, 30, 30]])

In [26]:
torch.mm(matrix1,matrix2)

tensor([[12, 12, 12],
        [30, 30, 30]])

In [27]:
matrix1@matrix2

tensor([[12, 12, 12],
        [30, 30, 30]])

# Back propagation

Backpropagation is a widely used algorithm for training feedforward neural networks. It computes the gradient of the loss function with respect to the network weights. It is very efficient, rather than naively directly computing the gradient concerning each weight.

if y=x^2 then backpropagtion will be y=2*x 
in simple words just derivative
backword matlab derivative nikalna

In [36]:
x=torch.tensor(4,dtype=float,requires_grad=True)

In [37]:
y=x**2
y

tensor(16., dtype=torch.float64, grad_fn=<PowBackward0>)

In [38]:
y.backward()

In [39]:
x.grad

tensor(8., dtype=torch.float64)

y=x^3+x^2
after back propagation equation will be
y=3x^2+2x

In [40]:
input=torch.tensor(([1,1],[1,0],[0,1],[0,0]),dtype=float,requires_grad=True)

In [41]:
input

tensor([[1., 1.],
        [1., 0.],
        [0., 1.],
        [0., 0.]], dtype=torch.float64, requires_grad=True)

In [42]:
y=input**3+input**2
y

tensor([[2., 2.],
        [2., 0.],
        [0., 2.],
        [0., 0.]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [44]:
output=y.sum()
output

tensor(8., dtype=torch.float64, grad_fn=<SumBackward0>)

In [45]:
output.backward()

In [46]:
input.grad

tensor([[5., 5.],
        [5., 0.],
        [0., 5.],
        [0., 0.]], dtype=torch.float64)

In [49]:
3*1**2+1*2

5

In [50]:
import pandas as pd

In [51]:
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [52]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [53]:
x=df.drop('Outcome',axis=1).values #independent features
y=df['Outcome'].values #dependent features

In [60]:
df.shape

(768, 9)

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_test,Y_train=train_test_split(x,y,test_size=0.2,random_state=0)

Independent features need to be converted into float tensors

In [57]:
X_train=torch.FloatTensor(X_train)
X_test=torch.FloatTensor(X_test)
Y_train=torch.LongTensor(Y_train)
Y_test=torch.LongTensor(Y_test)

# Creating Model with Pytorch 

In [58]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [61]:
class ANN_Model(nn.Module):
    def __init__(self,input_features=8,hidden1=20,hidden2=20,output_features=2):
        super().__init__()
        self.f_connected1=nn.Linear(input_features,hidden1)
        self.f_connected2=nn.Linear(hidden1,hidden2)
        self.out=nn.Linear(hidden2,output_features)
    def forward(self):
        x=F.relu(self.f_connected1(x))
        x=F.relu(self.f_connected2(x))
        x=self.out(x)
        return x

Instantiate my ANN Model

In [62]:
torch.manual_seed(20)
model=ANN_Model()

In [63]:
model.parameters

<bound method Module.parameters of ANN_Model(
  (f_connected1): Linear(in_features=8, out_features=20, bias=True)
  (f_connected2): Linear(in_features=20, out_features=20, bias=True)
  (out): Linear(in_features=20, out_features=2, bias=True)
)>

Backward propagation--> defining loss function and optimizer

In [66]:
loss_function=CrossEntropyLoss()

NameError: name 'CrossEntropyLoss' is not defined